version: "3.8"
services:
      mongo:
        image: mongo:latest
        container_name: mongod
        ports:  
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpassword
        volumes:
          - ./data1:/data/db
        
      mongonode:
        build:
          context: .
        ports:
          - 3000:3000
        container_name: node-mongo
        depends_on: [mongo]
      

          
